// <auto-generated> Regenerate with tools/Generate-Strings.ps1 after editing Strings.resx. </auto-generated>
#nullable enable
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace AppleDrive.Presentation.Resources;

/// <summary>
/// User-facing text. Values live in Strings.resx (add Strings.&lt;culture&gt;.resx to localize);
/// each property name is its resource key.
/// </summary>
public static class Strings
{
    private static readonly ResourceManager Manager =
        new("AppleDrive.Presentation.Resources.Strings", typeof(Strings).Assembly);

    public static string AppTitle => Get();

    public static string NavDashboard => Get();

    public static string NavImport => Get();

    public static string NavHistory => Get();

    public static string NavSettings => Get();

    public static string WelcomeTitle => Get();

    public static string WelcomeBody => Get();

    public static string WelcomeConnectHint => Get();

    public static string WelcomeGetStarted => Get();

    public static string DeviceSearchingTitle => Get();

    public static string DeviceNoneTitle => Get();

    public static string DeviceNoneBody => Get();

    public static string DeviceLockedTitle => Get();

    public static string DeviceLockedBody => Get();

    public static string DeviceUnavailableTitle => Get();

    public static string DeviceUnavailableBody => Get();

    public static string DeviceConnectedTitle => Get();

    public static string DeviceLabel => Get();

    public static string StatusLabel => Get();

    public static string StatusConnected => Get();

    public static string Refresh => Get();

    public static string ScanPhotos => Get();

    public static string Cancel => Get();

    public static string ShowDetails => Get();

    public static string Scanning => Get();

    public static string ScanningFoundFormat => Get();

    public static string ScanCompleteTitle => Get();

    public static string PhotosLabel => Get();

    public static string VideosLabel => Get();

    public static string LivePhotosLabel => Get();

    public static string FilesLabel => Get();

    public static string TotalSizeLabel => Get();

    public static string ScanNoMedia => Get();

    public static string ScanNoMediaBody => Get();

    public static string ScanCancelled => Get();

    public static string ErrorDeviceDisconnected => Get();

    public static string ErrorDeviceLocked => Get();

    public static string ErrorDeviceBusy => Get();

    public static string ErrorDeviceIo => Get();

    public static string ErrorGeneric => Get();

    public static string SettingsTitle => Get();

    public static string DestinationHeader => Get();

    public static string DestinationDescription => Get();

    public static string DestinationNotSet => Get();

    public static string Browse => Get();

    public static string OrganizationHeader => Get();

    public static string OrganizationDescription => Get();

    public static string OrganizationFlat => Get();

    public static string OrganizationYearMonth => Get();

    public static string OrganizationYearMonthDay => Get();

    public static string SkipDuplicatesHeader => Get();

    public static string SkipDuplicatesDescription => Get();

    public static string LogLevelHeader => Get();

    public static string LogLevelDescription => Get();

    public static string LogLevelDebug => Get();

    public static string LogLevelInformation => Get();

    public static string LogLevelWarning => Get();

    public static string LogLevelError => Get();

    public static string OpenLogsFolder => Get();

    public static string PrivacyHeader => Get();

    public static string PrivacyBody => Get();

    public static string AboutHeader => Get();

    public static string VersionFormat => Get();

    public static string HistoryEmptyTitle => Get();

    public static string HistoryEmptyBody => Get();

    public static string DestinationCardTitle => Get();

    public static string DestinationChooseBody => Get();

    public static string ChooseFolder => Get();

    public static string ChangeFolder => Get();

    public static string ScanDestination => Get();

    public static string DestinationScanning => Get();

    public static string DestinationScanningFormat => Get();

    public static string DestinationIndexedFormat => Get();

    public static string DestinationChangesFormat => Get();

    public static string DestinationNeverScanned => Get();

    public static string ErrorDestinationUnavailable => Get();

    public static string ErrorAccessDenied => Get();

    public static string ErrorDatabase => Get();

    public static string ImportIntroTitle => Get();

    public static string ImportIntroBody => Get();

    public static string CheckForNewPhotos => Get();

    public static string ImportNeedsDevice => Get();

    public static string ImportNeedsDestination => Get();

    public static string StageScanningPhone => Get();

    public static string StageScanningDestination => Get();

    public static string StageCheckingDuplicates => Get();

    public static string StageCountFormat => Get();

    public static string StageProgressFormat => Get();

    public static string TotalOnIphoneLabel => Get();

    public static string NewLabel => Get();

    public static string ExactDuplicatesLabel => Get();

    public static string TransferSizeLabel => Get();

    public static string DestinationLabel => Get();

    public static string UnverifiedFormat => Get();

    public static string NothingNewTitle => Get();

    public static string NothingNewBody => Get();

    public static string CheckAgain => Get();

    public static string StartTransfer => Get();

    public static string ConfirmTransferTitle => Get();

    public static string ConfirmNewLabel => Get();

    public static string ConfirmDuplicatesLabel => Get();

    public static string ConfirmSizeLabel => Get();

    public static string ConfirmOrganizationLabel => Get();

    public static string ConfirmFootnote => Get();

    public static string Transferring => Get();

    public static string TransferItemsFormat => Get();

    public static string TransferCurrentFormat => Get();

    public static string TransferSpeedFormat => Get();

    public static string TransferRemainingFormat => Get();

    public static string TransferStarting => Get();

    public static string TransferredLabel => Get();

    public static string SkippedLabel => Get();

    public static string FailedLabel => Get();

    public static string CopiedLabel => Get();

    public static string TransferCompleteTitle => Get();

    public static string TransferCancelledTitle => Get();

    public static string TransferStoppedTitle => Get();

    public static string TransferRemainingItemsFormat => Get();

    public static string TransferFailedFormat => Get();

    public static string ViewFailedFiles => Get();

    public static string RetryFailed => Get();

    public static string CopyRemaining => Get();

    public static string OpenFolder => Get();

    public static string Done => Get();

    public static string ErrorDestinationFull => Get();

    public static string ErrorVerificationFailed => Get();

    public static string ErrorDestinationIo => Get();

    public static string ErrorSourceUnavailable => Get();

    public static string DurationHoursFormat => Get();

    public static string DurationMinutesFormat => Get();

    public static string DurationSecondsFormat => Get();

    public static string StagePreparingVisualCheck => Get();

    public static string StageComparingVisually => Get();

    public static string PossibleDuplicatesLabel => Get();

    public static string PossibleDuplicatesExplanation => Get();

    public static string ConfirmPossibleDuplicatesLabel => Get();

    public static string ConfirmIncludePossibleDuplicatesFormat => Get();

    public static string VisuallyUncheckedFormat => Get();

    public static string PossibleDuplicatesCopiedLabel => Get();

    public static string PossibleDuplicatesSkippedLabel => Get();

    public static string ReviewFiles => Get();

    public static string ReviewTitle => Get();

    public static string Back => Get();

    public static string ReviewNoPlan => Get();

    public static string NoItemsMatch => Get();

    public static string SearchPlaceholder => Get();

    public static string FilterStatusAll => Get();

    public static string FilterStatusNew => Get();

    public static string FilterStatusPossible => Get();

    public static string FilterStatusExisting => Get();

    public static string FilterTypeAll => Get();

    public static string FilterTypePhotos => Get();

    public static string FilterTypeVideos => Get();

    public static string AllYears => Get();

    public static string SortNewest => Get();

    public static string SortOldest => Get();

    public static string SortName => Get();

    public static string SortSize => Get();

    public static string SortStatus => Get();

    public static string FilterStatusLabel => Get();

    public static string FilterTypeLabel => Get();

    public static string FilterYearLabel => Get();

    public static string SortLabel => Get();

    public static string SelectAll => Get();

    public static string SelectNone => Get();

    public static string SelectOnlyNew => Get();

    public static string IncludePossibleDuplicatesToggle => Get();

    public static string SelectedFormat => Get();

    public static string ShownFormat => Get();

    public static string SelectionOnPlanFormat => Get();

    public static string KindPhoto => Get();

    public static string KindVideo => Get();

    public static string KindLivePhoto => Get();

    public static string DateUnknown => Get();

    public static string StatusNew => Get();

    public static string StatusPossibleDuplicate => Get();

    public static string StatusAlreadyInDestination => Get();

    public static string ExistingFormat => Get();

    public static string LooksLikeFormat => Get();

    public static string SimilarityVeryHigh => Get();

    public static string SimilarityHigh => Get();

    public static string ItemCopy => Get();

    public static string ItemKeepBoth => Get();

    public static string OnIphoneLabel => Get();

    public static string InDestinationLabel => Get();

    /// <summary>Formats a resource string with the current culture.</summary>
    public static string Format(string format, params object?[] arguments) =>
        string.Format(CultureInfo.CurrentCulture, format, arguments);

    private static string Get([CallerMemberName] string key = "") =>
        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;
}
