<#
.SYNOPSIS
    Regenerates src/AppleDrive.Presentation/Resources/Strings.cs from Strings.resx.

.DESCRIPTION
    Strings.resx is the source of truth for user-facing text. After adding or removing an
    entry, run this script so the typed Strings accessor matches:

        powershell -ExecutionPolicy Bypass -File tools/Generate-Strings.ps1
#>
$ErrorActionPreference = 'Stop'
$resourceFolder = Join-Path $PSScriptRoot '..\src\AppleDrive.Presentation\Resources'
$resx = [xml](Get-Content -LiteralPath (Join-Path $resourceFolder 'Strings.resx') -Encoding UTF8)
$names = @($resx.root.data | ForEach-Object { $_.name })

$builder = New-Object System.Text.StringBuilder
[void]$builder.AppendLine('// <auto-generated> Regenerate with tools/Generate-Strings.ps1 after editing Strings.resx. </auto-generated>')
[void]$builder.AppendLine('#nullable enable')
[void]$builder.AppendLine('using System.Globalization;')
[void]$builder.AppendLine('using System.Resources;')
[void]$builder.AppendLine('using System.Runtime.CompilerServices;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('namespace AppleDrive.Presentation.Resources;')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('/// <summary>')
[void]$builder.AppendLine('/// User-facing text. Values live in Strings.resx (add Strings.&lt;culture&gt;.resx to localize);')
[void]$builder.AppendLine('/// each property name is its resource key.')
[void]$builder.AppendLine('/// </summary>')
[void]$builder.AppendLine('public static class Strings')
[void]$builder.AppendLine('{')
[void]$builder.AppendLine('    private static readonly ResourceManager Manager =')
[void]$builder.AppendLine('        new("AppleDrive.Presentation.Resources.Strings", typeof(Strings).Assembly);')
[void]$builder.AppendLine('')
foreach ($name in $names) {
    [void]$builder.AppendLine("    public static string $name => Get();")
    [void]$builder.AppendLine('')
}
[void]$builder.AppendLine('    /// <summary>Formats a resource string with the current culture.</summary>')
[void]$builder.AppendLine('    public static string Format(string format, params object?[] arguments) =>')
[void]$builder.AppendLine('        string.Format(CultureInfo.CurrentCulture, format, arguments);')
[void]$builder.AppendLine('')
[void]$builder.AppendLine('    private static string Get([CallerMemberName] string key = "") =>')
[void]$builder.AppendLine('        Manager.GetString(key, CultureInfo.CurrentUICulture) ?? key;')
[void]$builder.AppendLine('}')

$utf8 = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText((Join-Path $resourceFolder 'Strings.cs'), $builder.ToString(), $utf8)
"Generated Strings.cs with $($names.Count) entries"
